### ISSUE TITLE
Consider Microsoft.Extensions.Logging usage

### ISSUE THREAD

**Issue by rwkarg** [Delubear/GlucoseTray#15]
**Is your feature request related to a problem? Please describe.**
Current ILog is custom and doesn't have already built implementations.

**Describe the solution you'd like**
Use Microsoft.Extensions.Logging as a logging interface.
Packages and services would depend on injected `ILogger<T>` only.
Bootstrapping would configure an existing logging implementation like Serilog that has already built sinks for many log destinations:
https://github.com/serilog/serilog/wiki/Provided-Sinks 

**Describe alternatives you've considered**

**Additional context**

**Comment by Delubear** [comment]
Using the Microsoft ILogger was my plan, I just haven't had the time to properly look at and implement it. Will tag this as one of the next steps to do.

**Comment by Delubear** [comment]
Added serilog and Ilogger, just pointing to rolling text file for now.  More room for cleanup and updates to serilog configuration.

**Comment by Delubear** [comment]
Implemented, created new task to cleanup and optimize. #16
