### ISSUE TITLE
Font is odd

### ISSUE THREAD

**Issue by gitanO0** [Delubear/GlucoseTray#23]
The font on my laptop is pretty bad.  Any way to sharpen that up, like the clock text or the other text items in my screenshot?  Those other numbers are from "core temp" app.
![Annotation 2019-08-30 190324](https://user-images.githubusercontent.com/6887761/64057358-123c9980-cb59-11e9-946f-d7b5f3f49074.png)

**Comment by Delubear** [comment]
Will look into seeing what adjustments I can make to the IconService to increase the icon/text resolution.

**Comment by gitanO0** [comment]
I downloaded the code and fired up VS and was able to really improve the text by changing/adding the following:
private readonly Font fontToUse = new Font("Microsoft Sans Serif", 10, FontStyle.Regular, GraphicsUnit.Pixel);

            g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
            g.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality;

            g.ScaleTransform(.9f, 1.1f);
            g.DrawString(str, fontToUse, brushToUse, -3, 2);

![2019-10-02_12-34-37](https://user-images.githubusercontent.com/6887761/66071837-14f02d00-e511-11e9-96aa-73b1d357459b.png)
