### ISSUE TITLE
Display in mmol

### ISSUE THREAD

**Issue by Schoggiweggli** [Delubear/GlucoseTray#24]
Would be great if it was possible to display glucose values in mmol.

**Comment by Delubear** [comment]
Should hopefully have this out today after I can get some testing with it in.

**Comment by Delubear** [comment]
@Schoggiweggli 
Added in release 4.1 https://github.com/Delubear/GlucoseTray/releases/tag/4.1

Care to give it a try?  There is a new option in the settings file for switching it to MMOL.  Be sure to update your threshholds for high/low valies. (Right now it only accepts whole numbers, I will work on supporting decimal values like 5.5 soon.)

**Comment by Delubear** [comment]
version 4.2 supports decimal values in the thresholds.

https://github.com/Delubear/GlucoseTray/releases/tag/4.2

**Comment by Schoggiweggli** [comment]
Seems to work fine so far in V 4.2
