### ISSUE TITLE
Mark readings that are out-of-date

### ISSUE THREAD

**Issue by YPOC** [Delubear/GlucoseTray#28]
It would be nice if it was possible to mark values that are older than x minutes. It could be a strikethrough, or a solid background color, or maybe a red bar above and below the text. If the readings are stale you might run into trouble if you don't check another source.

It should be configurable after how many minutes a value is marked out-of-date

**Comment by sgmoore** [comment]
I have just added a Pull Request to do this.

I actually had done this for myself (on my forked repo) a month or two back.

**Comment by YPOC** [comment]
Works perfectly with the latest release. Thank you very much sgmoore & Delubear!
