### ISSUE TITLE
PollingThreshold is zero

### ISSUE THREAD

**Issue by sgmoore** [Delubear/GlucoseTray#31]
Using 8.3.0

Just got a warning that my free Papertrail service has reached its log data transfer limit of 10 MB for today and it appears that PollingThreshold is not being read from the appsettings.json which means GlucoseTray is hitting NightScout several times a second.

Have not had much chance to debug, but I suspect it might need to be declared public rather than private.

**Comment by Delubear** [comment]
Thanks for finding this.

Just pushed an update and if you can let me know if its fixed in version 8.3.1 that would be great.  The release should be out in a few minutes.

**Comment by Delubear** [comment]
Release is here: https://github.com/Delubear/GlucoseTray/releases/tag/8.3.1

Or build using commit https://github.com/Delubear/GlucoseTray/commit/32ef2e397f437e975ad631d5294f78ab1e6b14f1 and onward.

**Comment by sgmoore** [comment]
Yes that fixes it.

Thanks.
