### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by PolicarpoC** [Delubear/GlucoseTray#57]
After the config screen he just dont shows up on task bar.

He ask for download data from nightscout but nothing happens.

**Comment by Delubear** [comment]
Can you try closing the program and deleting this file?

C:\Users\<username>\AppData\Roaming\GlucoseTrayCore\GlucoseTrayCore\1.0.0\glucose_tray_settings.json

Then try running again.  When entering your nightscout URL, ensure not to include the trailing / to see if that resolves the issue.

**Comment by prakashdevadas69** [comment]
Hi Any idea why i am getting this error
'string was not recognized as valid DateTime'

**Comment by sgmoore** [comment]
> Hi Any idea why i am getting this error
Nothing stands out

What version are you running?
Does your event log show any more details or any previous errors?
What version of .Net are you running?

This message is a little puzzling. 

The standard FormatException would get under .NetCore 3.1 and greater and under .Net Framework 5 and greater should show what string you are trying to convert. Even for empty strings you get a message  **String '' was not recognized as a valid DateTime.** And I don't think this project would run on earlier frameworks. 

The error message displayed in the MessageBox **should** contain the full exception including the stack trace to pinpoint where the error occurred.

**Comment by prakashdevadas69** [comment]
> > Hi Any idea why i am getting this error
> > Nothing stands out
> 
> What version are you running? Does your event log show any more details or any previous errors? What version of .Net are you running?

Trayscout 1.5 is the version.
But the issue was noticed with one specific nightscout url where as with other nightscout url it is working.
May be some issue with nightscout settings .. 
Any clue to be checked in nightscout

**Comment by prakashdevadas69** [comment]
> > Hi Any idea why i am getting this error
> > Nothing stands out
> 

Hi,
Sorry I was trying the other software..now I tried with version Glucose Tray 12.0.0
this is error . How to get the logs  as requested
![image](https://user-images.githubusercontent.com/75934692/173198749-002c6098-5454-4231-aa92-5dd387b5b554.png)

**Comment by sgmoore** [comment]
The only way I can see this error occurring was if you were using NightScout and either there are absolutely no records in your NightScout database or there is something unexpected with the results.

Can you try browsing to a url in the format https://xxxx/api/v1/entries/sgv.json?count=1&token=yyyy

where xxx is your domain name and yyyy is the access token.

Does this give you any results?

Failing that you need to look for event log messages, i.e. Click on **Start** and type **Event Viewer** , Expand **Windows Logs** and select **Application** and then look for messages with the Source as **.NET Runtime** and which mention GlucoseTray in the category.

**Comment by prakashdevadas69** [comment]
> The only way I can see this error occurring was if you were using NightScout and either there are absolutely no records in your NightScout database or there is something unexpected with the results.
> 
> 
> 
> Can you try browsing to a url in the format https://xxxx/api/v1/entries/sgv.json?count=1&token=yyyy
> 
> 
> 
> where xxx is your domain name and yyyy is the access token.
> 
> 
> 
> Does this give you any results?
> 
> 
> 
> Failing that you need to look for event log messages, i.e. Click on **Start** and type **Event Viewer** , Expand **Windows Logs** and select **Application** and then look for messages with the Source as **.NET Runtime** and which mention GlucoseTray in the category.

Hi,
Sorry for the late reply
Url gives following

![image](https://user-images.githubusercontent.com/75934692/174349370-7a654038-0484-472a-96f5-974a29b856f5.jpeg)

**Comment by prakashdevadas69** [comment]
> The only way I can see this error occurring was if you were using NightScout and either there are absolutely no records in your NightScout database or there is something unexpected with the results.
> 
> 
> 
> Can you try browsing to a url in the format https://xxxx/api/v1/entries/sgv.json?count=1&token=yyyy
> 
> 
> 
> where xxx is your domain name and yyyy is the access token.
> 
> 
> 
> Does this give you any results?
> 
> 
> 
> Failing that you need to look for event log messages, i.e. Click on **Start** and type **Event Viewer** , Expand **Windows Logs** and select **Application** and then look for messages with the Source as **.NET Runtime** and which mention GlucoseTray in the category.

Hi
Sorry for the late reply. Url gives following output. ![image](https://user-images.githubusercontent.com/75934692/174349684-753983d3-b776-4255-badf-a00ab94b66c4.jpeg)

**Comment by sgmoore** [comment]
I think I see the problem now as your result is missing the dateString field which GlucoseTray is using.

It appears the Tomato app does not send this to Nightscout and is the same as this issue [https://github.com/StephenBlackWasAlreadyTaken/NightWatch/issues/117](https://github.com/StephenBlackWasAlreadyTaken/NightWatch/issues/117)  

Can you check that you are running the latest version of the Tomato app just in case they have already fixed the issue with their app?

Otherwise we should have a workaround on the next release.

**Comment by tannygamer007** [comment]
Thank you..we are using latest version of Tomato..
Probably your work around will help us...Pls release it as soon as possible..

**Comment by sgmoore** [comment]
This should be released now.

Can you check that the time is reported accurately especially regarding your time-zone. For example, double click on the tray icon and it should display the last result and the time it occurred.

eg
![image](https://user-images.githubusercontent.com/754367/174426828-f68e81d8-8e20-4d5a-b515-0ae0950ba9d5.png)

**Comment by prakashdevadas69** [comment]
> This should be released now.
> 
> 
> 
> Can you check that the time is reported accurately especially regarding your time-zone. For example, double click on the tray icon and it should display the last result and the time it occurred.
> 
> 
> 
> eg
> 
> ![image](https://user-images.githubusercontent.com/754367/174426828-f68e81d8-8e20-4d5a-b515-0ae0950ba9d5.png)
> 
> 

This is working
Thank you so much for the quick fix..

**Comment by prakashdevadas69** [comment]
Hi
In some PC I am getting symbol like this..but when cursor shows readings. Any suggestions pls..


![image](https://user-images.githubusercontent.com/75934692/175450072-a677a390-f8fd-4cd0-881c-a8af36c3105f.jpeg)

**Comment by Delubear** [comment]
I find having a darker or more transparent taskbar color can help.  You could also try to change your warning thresholds if it is just the yellow being troublesome.  We're sort of limited with the options we have with fonts and pixels as a tray icon.

**Comment by Delubear** [comment]
The above image is fixed in the latest release.  It includes a light/dark mode as well as higher resolution text.
