### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by alfureu** [Delubear/GlucoseTray#59]
Would it be please possible to introduce an option for font selection (maybe even with some spacing around and color-coding based on value/alert)? On HiDPI monitors the current font is rather choppy and does not show clearly the reading. Thanks!

![image](https://user-images.githubusercontent.com/10846169/147825800-f34bf7ce-fe2d-48c4-94f6-21d20ecfa095.png)

**Comment by Delubear** [comment]
I'll add it as something to take a look at.  We're limited with fonts as we have to fit up to 3 numbers and a period in a very small pixel constraint and it's taken a lot of work to get it to fit as is.  The current font was chosen due to how narrow it is.

**Comment by alfureu** [comment]
Thanks, much appreciated! I wonder whether you have to stay within those pixel constraints, as there are taskbar apps which do not follow this rule, e.g.:

- https://github.com/White-Tiger/T-Clock - with this one can introduce as long time / date / etc. combinations as one wishes (screenshot below)

![image](https://user-images.githubusercontent.com/10846169/147894677-5496346f-a7a3-420e-828d-9183a268c248.png)

The other option is not putting it into the taskbar but rather as a Toolbar (i.e., the part left to the taskbar).

- https://github.com/zhongyang219/TrafficMonitor - for example this app puts all the data into the Toolbar, where is much more space, and it is always visible (see screenshot below)

![image](https://user-images.githubusercontent.com/10846169/147894740-eb02c901-241a-4477-869f-1f6f4f9429a1.png)

Maybe these apps can be helpful to find a solution?

**Comment by sgmoore** [comment]
Just my opinion, but I am not sure if the 'enhanced' taskbar option is a good idea.

Some time back, I briefly looked at this (mainly because I thought it might be nice to include the direction/arrow as well as the current reading). But I decided against it as it appears Microsoft have deprecated support for such things and looking at the issues on those two projects it appears they both require hacks for them to work with Windows 11. It is entirely possible that the hacks will stop working on the next version of Windows.

**Comment by Delubear** [comment]
I think Windows 11 is adding widgets back, is it not?  https://www.microsoft.com/en-us/windows/remote-resource-center/top-windows-Widgets-to-know-about?r=1

Ideally, it would be great to add an option for that, complete with a graph, but I don't think Windows 10 has any support for that either.  Nor would that always be visible/ontop of everything.

In the initial post, it appears to be not so much the font, but the left side of the 8 being slightly clipped from our lack of pixel space.  MMOL readings have been challenging with having the decimal place.

Open to more thoughts and discussion on this though.

**Comment by sergiotome** [comment]
I don't know if it is needed to have an option to select the font, but at least the app should be updated with a font that is legible. Here is an example of how this looks like in my computer. it is almost impossible to understand what the number displayed is....

![image](https://user-images.githubusercontent.com/16870246/223481433-48826cbc-d4d4-4eea-837d-2895bcc00eae.png)

**Comment by Delubear** [comment]
Looks to be an issue with the Windows light theme.  Probably need to add a dark mode toggle.

**Comment by Delubear** [comment]
You can try release 14.1.0.  That adds a Dark Mode toggle, but by default it should use colors more appropriate for Light Mode.  It still isn't perfect as the text drawing adds a black border or shadow which obscures the text to an extent, and I did not see a way to resolve that.  But it should no longer be drawing white on white in that scenario.

https://github.com/Delubear/GlucoseTray/releases/tag/14.1.0

**Comment by sergiotome** [comment]
This new version is better but still not good (see screenshot below). Can the app instead use a font that is not as thick so that it is easier to read? Something like the numbers on the clock on the right side of the screenshot?

![image](https://user-images.githubusercontent.com/16870246/223665360-d5111d12-4fed-435c-a823-db66874928de.png)

**Comment by Delubear** [comment]
No, not that I've been able to find. The icon tray is not intended for showing text.

**Comment by Delubear** [comment]
Was able to increase resolution from 16px to 64px in 14.2.0.

https://github.com/Delubear/GlucoseTray/releases/tag/14.2.0
