### ISSUE TITLE
not receiving CGM data (Dexcom EU)

### ISSUE THREAD

**Issue by actsour** [Delubear/GlucoseTray#63]
Edit: This might just be [Issue 62](https://github.com/Delubear/GlucoseTray/issues/62) (which is closed), however I'm receiving the same behavior with the latest version

first of all, a big thanks to all the contributors. This is a very useful tool and all your efforts are much appreciated!

However, unfortunately it doesn't work for me as I am not receiving any glucose readings. What I'm getting is this screen which keeps displaying the same values (something weird is going on with the time):

![issue](https://user-images.githubusercontent.com/98657859/191766748-67ea39ee-086c-4218-9a47-9e6829cd3950.jpg)

I followed the Setup Guide, and I'm trying to get the data from the Dexcom servers (I live in the EU and can therefore only login to clarity.dexcom.<ins>eu</ins>; *not* clarity.dexcom.com). So I selected the International server. 
My settings (I also get the "Settings saved" window without errors after confirming):

![issue0](https://user-images.githubusercontent.com/98657859/192006743-3eacc95e-8c46-4b3d-b932-5b5bc13631f5.jpg)

What I tried: 
- Allowing the application through Windows firewall
- trying every other server option
- triple checking Dexcom username and password (they are valid)
- deleting the glucose_tray_settings.json und trying again

But unfortunately the result was unchanged.

Maybe this could be an issue with the Dexcom EU/International Server? 
Or could this be caused by my Dexcom username being an e-mail address (containing multiple '.' [period] and '@')?

Im running the latest version of Glucose Tray 13.1.1 on Windows 10 and .NET Version 4.8.4048.0

Maybe someone can help me getting those CGM readings to my desktop at a glance.
Thank you!

**Comment by Delubear** [comment]
Can you try version 13.2.0 when it's available in a few minutes?  There will be a new settings option labelled Debug Mode.  If you could check that on and hit save, it should give you a popup notification the next time it tries to pull data and there is an error.  Then if you could send the contents of that message here, I can look into it further.   I have found nothing on the EU servers changing.

**Comment by actsour** [comment]
> Can you try version 13.2.0 when it's available in a few minutes? There will be a new settings option labelled Debug Mode. If you could check that on and hit save, it should give you a popup notification the next time it tries to pull data and there is an error. Then if you could send the contents of that message here, I can look into it further. I have found nothing on the EU servers changing.

Thank you for your fast reply! I did try it with the new version 13.2.0 and its debug mode keeps throwing the following error:

![grafik](https://user-images.githubusercontent.com/98657859/192040081-74a07a5b-9cbb-4177-9d47-e1c69d9abd29.png)

I also tried it on a different machine (older laptop running Windows 7) and I got a different error message there:

![Win7Error](https://user-images.githubusercontent.com/98657859/192040376-bb28733a-a748-41ea-82a6-72e8ada30e71.png)

Hopefully this is helpful in some way. Just let me know if I can provide more information.

**Comment by Delubear** [comment]
I will probably need to add another build for you to try to find out exactly what it is returning and how it's failing.  Dexcom international may have changed or started doing things differently.

**Comment by Delubear** [comment]
Should be ready soon, but can you try the same with build 13.2.3?  It should be setup to log a step by step breakdown of the respones we're getting back from dexcom.

**Comment by Delubear** [comment]
https://github.com/Delubear/GlucoseTray/releases/tag/13.2.3

**Comment by actsour** [comment]
Sure! Thanks so much for your help. With build 13.2.3 i get the following message:

![grafik](https://user-images.githubusercontent.com/98657859/192065730-56f56d9c-5637-4e62-b436-81af4efdc287.png)

**Comment by Delubear** [comment]
Sorry, one more version to test: 13.2.4.  Should be ready soon.  I didnt expect to have to debug that far up the chain, but it looks like its failing to get a session id, so next thing is we need to know if its failing to get an account id.

**Comment by Delubear** [comment]
https://github.com/Delubear/GlucoseTray/releases/tag/13.2.4

**Comment by actsour** [comment]
Thanks again, to me it looks like getting the account ID is working:

![error](https://user-images.githubusercontent.com/98657859/192087371-70fb403a-8df2-441d-befa-824bc1b05446.png)

Interestingly, it's showing the correct time now. This wasn't the case before (at least with 13.1.1)
![error](https://user-images.githubusercontent.com/98657859/192087500-fdc69fe4-a985-480e-b8a4-f6f772315a86.png)

**Comment by Delubear** [comment]
Version 13.3.0 will be available soon.  It should fix your issue.  It appears when using the Account Id change from the last reported issue, for newer accounts that use emails, it needs a slightly different endpoint to properly validate the account using the id.

**Comment by actsour** [comment]
Works perfectly now with v13.3.0, so this issue has been resolved. Thank you so much @Delubear for your work and support! 🥇
If you could use help for testing or the like in the future, just let me know.

**Comment by Delubear** [comment]
Thanks for reporting the issue. I don't have the capability for testing newer style or international accounts myself so thank you for the assist. This should fix it for quite a number of others as well going forward.
