### ISSUE TITLE
153 MB for this??

### ISSUE THREAD

**Issue by ags1234** [Delubear/GlucoseTray#70]
The size of this program is absolutely insanely big for what it is and what it does. It needs to be developed with a different technology, for optimization.
I would not consider using it as it is now, because it wastes my resources. And if it wastes my resources, it does not respect me.
Of course everyone has storage space for it nowadays, that is not really the problem.
What I am referring to here is a problem of efficiency.

**Comment by Delubear** [comment]
It's the size it is since it bundles the .net runtime.  This prevents requiring users having to go download and install that themselves, and then needing to update it when the version changes.
