### ISSUE TITLE
No Result being returned []

### ISSUE THREAD

**Issue by FtrSpec** [Delubear/GlucoseTray#72]
**Describe the bug**
Share1 and Share2 Dexcom servers are communicating, validating login, generating a session, but when fetching the results are returning nothing "[]".  Tried in debugger and downloadable exe.  You are getting data from previous calls to generate url: https://share1.dexcom.com/ShareWebServices/Services/Publisher/ReadPublisherLatestGlucoseValues?sessionId=ab..5bd&minutes=1440&maxCount=1, but then that url is returning an OK response but doesn't seem to have any data.

**To Reproduce**
Enter login details for Dexcom, use dexcom server share1 or share2.  Every fetch get error about deserializing because server is returning [], nothing to deserialize.

**Expected behavior**
Server should be returning last GCM reading and deserialize should be able to parse the return.

**Screenshots**
---------------------------
DexCom result fetch
---------------------------
Sequence contains no elementsStarting DexCom Fetch Server: share2.dexcom.com Sending Account Id Request. Status code: OK Got a valid account id Sending Session Id Request. Status code: OK Got a valid session id Sending Gluocse Event Request. Status code: OK Result: [] Attempting to deserialize
---------------------------
OK   
---------------------------

**Desktop (please complete the following information):**
Windows 11

**Smartphone (please complete the following information):**
Android Pixel

**Additional context**
Something going array in final communication, figured I'd need to add your app to access my account or something (even with providing clarity credentials)?  Doesn't appear so, or maybe I've overlooked those instructions, don't see a way to do that on website or mobile app.

**Comment by Delubear** [comment]
This seems like you may be using an account that doesn't have any readings available. It should be the same account that you are signed into the dexcom app with. 

Possible that dexcom may have changed something again but mine is working and haven't seen any other reports yet.  It may be a delayed to rollout if it is something on their end, but I would start by making sure you're entering the credentials for the correct.

**Comment by Delubear** [comment]
If this is still an issue with the latest version, please leave a comment.
