### ISSUE TITLE
Glucose tray v15.1.6 displays glucose value in RED on taskbar when reading is within range

### ISSUE THREAD

**Issue by rdh76** [Delubear/GlucoseTray#74]
Glucose tray v15.1.6 displays glucose value in RED on taskbar when reading is within range. Current glucose is 95 but displays as red.

Screen shot below is my current settings.

![Screenshot 2024-09-25 160857](https://github.com/user-attachments/assets/b95441a4-b4fa-42be-8e96-5cb62f86267a)

**Comment by rdh76** [comment]
Thank you for providing this excellent app.

**Comment by Delubear** [comment]
Thank you for reporting this.  Version 15.1.8 is now in the pipeline and should be available in a few minutes that should address this.
